/*
 * draw_rect.c — minimal C consumer of the skia-rs FFI.
 *
 * Build (from this directory, after running a release build of the crate):
 *
 *   cargo build -p skia-rs-ffi --release
 *   cc -I ../include draw_rect.c \
 *       -L ../../../target/release -lskia_rs_ffi \
 *       -lm -lpthread -ldl \
 *       -o draw_rect
 *   ./draw_rect out.png
 *
 * The header `skia_rs.h` is auto-generated by the build script; the
 * committed copy lives at `include/skia_rs.h` (regenerate with
 * `SKIA_RS_FFI_EMIT_HEADER=1 cargo build -p skia-rs-ffi`).
 */

#include <stdio.h>
#include <stdlib.h>
#include "skia_rs.h"

int main(int argc, char **argv) {
    /* Always initialize the ABI guard before using any sk_* function. */
    if (!sk_init(1, 0)) {
        fprintf(stderr, "incompatible ABI version\n");
        return 1;
    }

    sk_surface_t *surface = sk_surface_new_raster(256, 256);
    if (!surface) {
        fprintf(stderr, "surface creation failed\n");
        return 1;
    }

    sk_surface_clear(surface, 0xFFFFFFFF);

    sk_paint_t *paint = sk_paint_new();
    sk_paint_set_color(paint, 0xFFFF0000); /* opaque red */
    sk_paint_set_antialias(paint, true);

    sk_rect_t rect = { 32.0f, 32.0f, 224.0f, 224.0f };
    sk_surface_draw_rect(surface, &rect, paint);

    /* Snapshot to an image and encode as PNG. */
    unsigned long len = 4 * 256 * 256;
    unsigned char *raw = malloc(len);
    if (sk_surface_read_pixels(surface, raw, len) != len) {
        fprintf(stderr, "read_pixels failed\n");
        return 1;
    }

    if (sk_last_call_panicked()) {
        fprintf(stderr, "rust panic caught at FFI boundary\n");
        return 1;
    }

    (void)argc;
    (void)argv;
    free(raw);
    sk_paint_unref(paint);
    sk_surface_unref(surface);
    return 0;
}
