/*
 * skia-rs C API Header
 *
 * This file is auto-generated by cbindgen. Do not modify directly.
 *
 * Copyright 2026 Pegasus Heavy Industries
 * License: MIT OR Apache-2.0
 */


#ifndef SKIA_RS_H
#define SKIA_RS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Index constants for matrix elements.
#define Matrix_SCALE_X 0

// Skew X index.
#define Matrix_SKEW_X 1

// Translate X index.
#define Matrix_TRANS_X 2

// Skew Y index.
#define Matrix_SKEW_Y 3

// Scale Y index.
#define Matrix_SCALE_Y 4

// Translate Y index.
#define Matrix_TRANS_Y 5

// Perspective 0 index.
#define Matrix_PERSP_0 6

// Perspective 1 index.
#define Matrix_PERSP_1 7

// Perspective 2 index.
#define Matrix_PERSP_2 8

// Filter mode for image sampling.
enum FilterMode
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    // Nearest neighbor sampling.
    FilterMode_Nearest = 0,
    // Bilinear interpolation.
    FilterMode_Linear,
};
#ifndef __cplusplus
typedef uint8_t FilterMode;
#endif // __cplusplus

// Mipmap mode for image sampling.
enum MipmapMode
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    // No mipmapping.
    MipmapMode_None = 0,
    // Nearest mipmap level.
    MipmapMode_Nearest,
    // Linear interpolation between mipmap levels.
    MipmapMode_Linear,
};
#ifndef __cplusplus
typedef uint8_t MipmapMode;
#endif // __cplusplus

// Gradient flags for controlling interpolation.
typedef struct GradientFlags GradientFlags;

// Paint configuration for drawing operations.
typedef struct Paint Paint;

// A 2D geometric path.
typedef struct Path Path;

// Builder for constructing paths.
typedef struct PathBuilder PathBuilder;

// Sampling options for image shaders.
typedef struct SamplingOptions SamplingOptions;

// Opaque surface type.
typedef Surface SkSurface;

// C-compatible image info structure.
typedef struct sk_imageinfo_t {
    // Width.
    int32_t width;
    // Height.
    int32_t height;
    // Color type.
    uint32_t color_type;
    // Alpha type.
    uint32_t alpha_type;
} sk_imageinfo_t;

// Opaque paint type.
typedef struct Paint SkPaint;

// C-compatible color (ARGB).
typedef uint32_t sk_color_t;

// Opaque path type.
typedef struct Path SkPath;

// C-compatible rectangle structure.
typedef struct sk_rect_t {
    // Left edge.
    float left;
    // Top edge.
    float top;
    // Right edge.
    float right;
    // Bottom edge.
    float bottom;
} sk_rect_t;

// Opaque path builder type.
typedef struct PathBuilder SkPathBuilder;

// C-compatible matrix structure.
typedef struct sk_matrix_t {
    // Matrix values (row-major).
    float values[9];
} sk_matrix_t;

// C-compatible point structure.
typedef struct sk_point_t {
    // X coordinate.
    float x;
    // Y coordinate.
    float y;
} sk_point_t;

// A 32-bit ARGB color.
//
// Equivalent to Skia's `SkColor`. Format is 0xAARRGGBB.
typedef uint32_t Color;
// Transparent black.
#define Color_TRANSPARENT 0
// Opaque black.
#define Color_BLACK 4278190080
// Dark gray.
#define Color_DKGRAY 4282664004
// Gray.
#define Color_GRAY 4287137928
// Light gray.
#define Color_LTGRAY 4291611852
// Opaque white.
#define Color_WHITE 4294967295
// Opaque red.
#define Color_RED 4294901760
// Opaque green.
#define Color_GREEN 4278255360
// Opaque blue.
#define Color_BLUE 4278190335
// Opaque yellow.
#define Color_YELLOW 4294967040
// Opaque cyan.
#define Color_CYAN 4278255615
// Opaque magenta.
#define Color_MAGENTA 4294902015

// Transparent black.
#define COLOR_TRANSPARENT Color_TRANSPARENT

// Opaque black.
#define COLOR_BLACK Color_BLACK

// Dark gray.
#define COLOR_DKGRAY Color_DKGRAY

// Gray.
#define COLOR_GRAY Color_GRAY

// Light gray.
#define COLOR_LTGRAY Color_LTGRAY

// Opaque white.
#define COLOR_WHITE Color_WHITE

// Opaque red.
#define COLOR_RED Color_RED

// Opaque green.
#define COLOR_GREEN Color_GREEN

// Opaque blue.
#define COLOR_BLUE Color_BLUE

// Opaque yellow.
#define COLOR_YELLOW Color_YELLOW

// Opaque cyan.
#define COLOR_CYAN Color_CYAN

// Opaque magenta.
#define COLOR_MAGENTA Color_MAGENTA











#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Check if the last FFI call panicked.
//
// Returns true if a panic occurred, false otherwise.
// Reading this flag clears it.
bool sk_last_call_panicked(void);

// Create a new raster surface.
SkSurface *sk_surface_new_raster(int32_t width,
                                 int32_t height);

// Create a raster surface with specific image info.
SkSurface *sk_surface_new_raster_with_info(const struct sk_imageinfo_t *info);

// Delete a surface.
void sk_surface_unref(SkSurface *surface);

// Get the width of a surface.
int32_t sk_surface_get_width(const SkSurface *surface);

// Get the height of a surface.
int32_t sk_surface_get_height(const SkSurface *surface);

// Get the pixel data from a surface.
bool sk_surface_peek_pixels(const SkSurface *surface,
                            const uint8_t **out_pixels,
                            uintptr_t *out_row_bytes);

// Create a new paint.
SkPaint *sk_paint_new(void);

// Clone a paint.
SkPaint *sk_paint_clone(const SkPaint *paint);

// Delete a paint.
void sk_paint_delete(SkPaint *paint);

// Set the paint color.
void sk_paint_set_color(SkPaint *paint,
                        sk_color_t color);

// Get the paint color.
sk_color_t sk_paint_get_color(const SkPaint *paint);

// Set the paint style.
void sk_paint_set_style(SkPaint *paint,
                        uint32_t style);

// Set the stroke width.
void sk_paint_set_stroke_width(SkPaint *paint,
                               float width);

// Get the stroke width.
float sk_paint_get_stroke_width(const SkPaint *paint);

// Set anti-alias.
void sk_paint_set_antialias(SkPaint *paint,
                            bool aa);

// Check if anti-alias is enabled.
bool sk_paint_is_antialias(const SkPaint *paint);

// Create a new path.
SkPath *sk_path_new(void);

// Clone a path.
SkPath *sk_path_clone(const SkPath *path);

// Delete a path.
void sk_path_delete(SkPath *path);

// Get the path bounds.
void sk_path_get_bounds(const SkPath *path,
                        struct sk_rect_t *bounds);

// Check if path is empty.
bool sk_path_is_empty(const SkPath *path);

// Get the fill type.
uint32_t sk_path_get_filltype(const SkPath *path);

// Set the fill type.
void sk_path_set_filltype(SkPath *path,
                          uint32_t fill_type);

// Check if path contains a point.
bool sk_path_contains(const SkPath *path,
                      float x,
                      float y);

// Create a new path builder.
SkPathBuilder *sk_pathbuilder_new(void);

// Delete a path builder.
void sk_pathbuilder_delete(SkPathBuilder *builder);

// Move to a point.
void sk_pathbuilder_move_to(SkPathBuilder *builder,
                            float x,
                            float y);

// Line to a point.
void sk_pathbuilder_line_to(SkPathBuilder *builder,
                            float x,
                            float y);

// Quadratic bezier to a point.
void sk_pathbuilder_quad_to(SkPathBuilder *builder,
                            float cx,
                            float cy,
                            float x,
                            float y);

// Cubic bezier to a point.
void sk_pathbuilder_cubic_to(SkPathBuilder *builder,
                             float c1x,
                             float c1y,
                             float c2x,
                             float c2y,
                             float x,
                             float y);

// Close the path.
void sk_pathbuilder_close(SkPathBuilder *builder);

// Add a rectangle.
void sk_pathbuilder_add_rect(SkPathBuilder *builder,
                             const struct sk_rect_t *rect);

// Add an oval.
void sk_pathbuilder_add_oval(SkPathBuilder *builder,
                             const struct sk_rect_t *rect);

// Add a circle.
void sk_pathbuilder_add_circle(SkPathBuilder *builder,
                               float cx,
                               float cy,
                               float radius);

// Build the path (consumes the builder).
SkPath *sk_pathbuilder_detach(SkPathBuilder *builder);

// Set matrix to identity.
void sk_matrix_set_identity(struct sk_matrix_t *matrix);

// Set matrix to translate.
void sk_matrix_set_translate(struct sk_matrix_t *matrix,
                             float dx,
                             float dy);

// Set matrix to scale.
void sk_matrix_set_scale(struct sk_matrix_t *matrix,
                         float sx,
                         float sy);

// Set matrix to rotate (degrees).
void sk_matrix_set_rotate(struct sk_matrix_t *matrix,
                          float degrees);

// Concatenate two matrices.
void sk_matrix_concat(struct sk_matrix_t *result,
                      const struct sk_matrix_t *a,
                      const struct sk_matrix_t *b);

// Map a point through a matrix.
void sk_matrix_map_point(const struct sk_matrix_t *matrix,
                         const struct sk_point_t *point,
                         struct sk_point_t *result);

// Get the library version.
const char *sk_version(void);

// Check if the library is available.
bool sk_is_available(void);

// Clear a surface with a color.
void sk_surface_clear(SkSurface *surface,
                      sk_color_t color);

// Draw a rect on a surface.
void sk_surface_draw_rect(SkSurface *surface,
                          const struct sk_rect_t *rect,
                          const SkPaint *paint);

// Draw a circle on a surface.
void sk_surface_draw_circle(SkSurface *surface,
                            float cx,
                            float cy,
                            float radius,
                            const SkPaint *paint);

// Draw a path on a surface.
void sk_surface_draw_path(SkSurface *surface,
                          const SkPath *path,
                          const SkPaint *paint);

// Draw a line on a surface.
void sk_surface_draw_line(SkSurface *surface,
                          float x0,
                          float y0,
                          float x1,
                          float y1,
                          const SkPaint *paint);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SKIA_RS_H */

/* End of skia-rs C API */
